apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: onlineboutique
spec:
  host: frontend
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2